using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyController : MonoBehaviour
{

    public enum GhostNodeStatesEnum
    {
        respawning,
        leftNode,
        rightNode,
        centerNode,
        startNode,
        movingInNodes
    }

    public  GhostNodeStatesEnum ghostNodeState;
    public GhostNodeStatesEnum startGhostNodeState;
    public GhostNodeStatesEnum respawnState;


    public enum GhostType
    {
        red,
        blue,
        pink,
        orange
    }

     public GhostType ghostType;
     //public GhostType  respawnState;

     public GameObject ghostNodeLeft;
     public GameObject ghostNodeRight;
     public GameObject ghostNodeCenter;
     public GameObject ghostNodeStart;

     public MovementController movementController;

     public GameObject startingNode;

     public bool readyToLeaveHome = false;

     public GameManager gameManager;


     public bool  testRespawn = false;

     public bool isFrightened = false;

     public GameObject[] scatterNodes;

     public int scatterNodeIndex;

     public bool leftHomeBefore = false;

     public bool isVisible = true;

     public SpriteRenderer ghostSprite;
     public SpriteRenderer eyesSprite;

     public Animator animator;

     public Color color;

    // Start is called before the first frame update
    void Awake()
    {
        animator = GetComponent<Animator>();
        ghostSprite = GetComponent<SpriteRenderer>();
        

        gameManager = GameObject.Find("GameManager").GetComponent<GameManager>();
        movementController = GetComponent<MovementController>();
        if (ghostType == GhostType.red)
        {
            startGhostNodeState = GhostNodeStatesEnum.startNode;
            respawnState = GhostNodeStatesEnum.centerNode;
            startingNode = ghostNodeStart;
            
        }
        else if (ghostType == GhostType.pink)
        {
             
              startGhostNodeState = GhostNodeStatesEnum.centerNode;
            startingNode = ghostNodeCenter;
              respawnState = GhostNodeStatesEnum.centerNode;
        }
        else if (ghostType == GhostType.blue)
        {
             startGhostNodeState = GhostNodeStatesEnum.leftNode;
              respawnState = GhostNodeStatesEnum.leftNode;

              startingNode = ghostNodeLeft;
        }
        else if (ghostType == GhostType.orange)
        {
           startGhostNodeState = GhostNodeStatesEnum.rightNode;
            respawnState = GhostNodeStatesEnum.rightNode;

             startingNode = ghostNodeRight;

        }


    }
    public void Setup()
    {
      animator.SetBool("moving", false);

      ghostNodeState = startGhostNodeState;
      readyToLeaveHome = false;
      
      movementController.currentNode = startingNode;
      transform.position = startingNode.transform.position;
      
      movementController.direction = "";
      movementController.lastMovingDirection = "";

      scatterNodeIndex = 0;

      isFrightened = false;

      leftHomeBefore = false;

      if (ghostType == GhostType.red)
      {
          readyToLeaveHome = true;
          leftHomeBefore = true;
      }
      else if (ghostType == GhostType.pink)
      {
        readyToLeaveHome = true;
      }
      SetVisible(true);
    }

    // Update is called once per frame
    void Update()
    {
         if (ghostNodeState != GhostNodeStatesEnum.movingInNodes || !gameManager.isPowerPelletRunning)
         {
           isFrightened = false;
         }
         
         if (isVisible)
         {
          if (ghostNodeState != GhostNodeStatesEnum.respawning)
          {
            ghostSprite.enabled = true;
          }
          else
          {
            ghostSprite.enabled = false;
          }
           eyesSprite.enabled = true;
         }

         else
         {
           ghostSprite.enabled = false;
           eyesSprite.enabled = false;
         }

          if (isFrightened)
        {
          animator.SetBool("frightened", true);
          eyesSprite.enabled = false;
          ghostSprite.color = new Color(255, 255, 255, 255);
        }
        else
        {
           animator.SetBool("frightened", false);
           animator.SetBool("frightenedBlinking", false);

           ghostSprite.color = color;
        }

        if (!gameManager.gameIsRunning)
        {
          return;
        }
        
        if (gameManager.powerPelletTimer - gameManager.currentPowerPelletTime <= 3)
        {
            animator.SetBool("frightenedBlinking", true);
        }

        else
        {
          animator.SetBool("frightenedBlinking", false);
        }
             animator.SetBool("moving", true);

        if ( testRespawn == true)
        {
          readyToLeaveHome = false;
          ghostNodeState = GhostNodeStatesEnum.respawning;
          testRespawn = false;
        }

        if (movementController.currentNode.GetComponent<NodeController>().isSideNode)
        {
          movementController.SetSpeed(1);
        }
        else
        {
           if(isFrightened)
           {
            movementController.SetSpeed(1);
           }
           else if (ghostNodeState == GhostNodeStatesEnum.respawning)
           {
            movementController.SetSpeed(7);
           }
          else
          {
            movementController.SetSpeed(2);
          }
        }
    }

    public void SetFrightened(bool newIsFrightened)
    {
      isFrightened = newIsFrightened;

    }

    public void ReachedCenterOfNode(NodeController nodeController)
    {
      if (ghostNodeState == GhostNodeStatesEnum.movingInNodes)
      {
        leftHomeBefore = true;
        
        if (gameManager.currentGhostMode == GameManager.GhostMode.scatter)
        {
           DetermineGhostScatterModeDirection(); 
        }

        else if (isFrightened)
        {
          string direction = GetRandomDirection();
          movementController.SetDirection(direction);
        }

        else
        {
          if (ghostType == GhostType.red)
          {
            DetermineRedGhostDirecition();
          }
          else if (ghostType == GhostType.pink)
          {
            DeterminePinkGhostDirecition();
          }
          else if (ghostType == GhostType.blue)
          {
            DetermineBlueGhostDirecition();
          }
          else if (ghostType == GhostType.orange)
          {
            DetermineBlueGhostDirecition();
          }
        }

      }

      else if (ghostNodeState == GhostNodeStatesEnum.respawning)
      {

        string direction = "";

        if (transform.position.x == ghostNodeStart.transform.position.x && transform.position.y == ghostNodeStart.transform.position.y)
        {
          direction = "down";
        }

        else if (transform.position.x == ghostNodeCenter.transform.position.x && transform.position.y == ghostNodeCenter.transform.position.y)
        {
          if ( respawnState == GhostNodeStatesEnum.centerNode)
          {
            ghostNodeState = respawnState;
          }
          else if (respawnState == GhostNodeStatesEnum.leftNode)
          {
            direction = "left";
          }
          else if (respawnState == GhostNodeStatesEnum.rightNode)
          {
            direction = "right";
          }
        }

        else if (
                (transform.position.x == ghostNodeLeft.transform.position.x && transform.position.y == ghostNodeLeft.transform.position.y)
              || (transform.position.x == ghostNodeRight.transform.position.x && transform.position.y == ghostNodeRight.transform.position.y)
              )
          {
            ghostNodeState = respawnState;
          }

        else
        {
           direction = GetClosestDirecition(ghostNodeStart.transform.position);
        }

        movementController.SetDirection(direction);
      }

      else
      {
        if (readyToLeaveHome)
        {

          if (ghostNodeState == GhostNodeStatesEnum.leftNode)
          {
              ghostNodeState = GhostNodeStatesEnum.centerNode;
              movementController.SetDirection("right");
          }

          else if (ghostNodeState == GhostNodeStatesEnum.rightNode)
          {
            ghostNodeState = GhostNodeStatesEnum.centerNode;
            movementController.SetDirection("left");
          }

          else if (ghostNodeState == GhostNodeStatesEnum.centerNode)
          {
              ghostNodeState = GhostNodeStatesEnum.startNode;
              movementController.SetDirection("up");
          }

          else if (ghostNodeState == GhostNodeStatesEnum.startNode)
          {
              ghostNodeState = GhostNodeStatesEnum.movingInNodes;
              movementController.SetDirection("left");
          }
        }
      }
    }
        string GetRandomDirection()
     {
       List<string> possibleDirections = new List<string>();
       NodeController nodeController = movementController.currentNode.GetComponent<NodeController>();

       if (nodeController.canMoveDown && movementController.lastMovingDirection != "up")
       {
        possibleDirections.Add("down");
       }
       if (nodeController.canMoveDown && movementController.lastMovingDirection != "down")
       {
        possibleDirections.Add("up");
       }
       if (nodeController.canMoveDown && movementController.lastMovingDirection != "left")
       {
        possibleDirections.Add("right");
       }
       if (nodeController.canMoveDown && movementController.lastMovingDirection != "right")
       {
        possibleDirections.Add("left");
       }

       string direction = "";
       int randomDirectionIndex = Random.Range(0, possibleDirections.Count - 1);
       direction = possibleDirections[randomDirectionIndex];

       return direction;
     }



    void DetermineGhostScatterModeDirection()
     {

     }
    void DetermineRedGhostDirecition()
    {
      string direction = GetClosestDirecition(gameManager.pacman.transform.position);
      
      movementController.SetDirection(direction);
   
    }


    void DeterminePinkGhostDirecition()
    {
     string  pacmansDirection = gameManager.pacman.GetComponent<MovementController>().lastMovingDirection;
     float distanceBetweenNodes = 0.35f;

     Vector2 target = gameManager.pacman.transform.position;

     if (pacmansDirection == "left")
     {
      target.x -= distanceBetweenNodes * 2;
     }
     else if (pacmansDirection == "right")
     {
      target.x += distanceBetweenNodes * 2;
     }
     else if (pacmansDirection == "up")
     {
      target.y += distanceBetweenNodes * 2;
     }
     else if (pacmansDirection == "down")
     {
      target.y -= distanceBetweenNodes * 2;
     }

     string direction = GetClosestDirecition(target);
     movementController.SetDirection(direction);
    }


   void DetermineBlueGhostDirecition()
    {
     string  pacmansDirection = gameManager.pacman.GetComponent<MovementController>().lastMovingDirection;
     float distanceBetweenNodes = 0.35f;

     Vector2 target = gameManager.pacman.transform.position;

     if (pacmansDirection == "left")
     {
      target.x -= distanceBetweenNodes * 2;
     }
     else if (pacmansDirection == "right")
     {
      target.x += distanceBetweenNodes * 2;
     }
     else if (pacmansDirection == "up")
     {
      target.y += distanceBetweenNodes * 2;
     }
     else if (pacmansDirection == "down")
     {
      target.y -= distanceBetweenNodes * 2;
     }
      GameObject redGhost = gameManager.redGhost;
      float xDistance = target.x - redGhost.transform.position.x;
      float yDistance = target.y - redGhost.transform.position.y;

      Vector2 blueTarget = new Vector2(target.x + xDistance, target.y + yDistance);
      string direction = GetClosestDirecition(blueTarget);
      movementController.SetDirection(direction);
    }

   void DetermineOrangrGhostDirecition()
    {
       float distance = Vector2.Distance(gameManager.pacman.transform.position, transform.position);
      float distanceBetweenNodes = 0.35f;;

       if (distance < 0)
       {
        distance *= -1;
       }


        if (distance <= distanceBetweenNodes * 8)
        {
          DetermineBlueGhostDirecition();
        }

        else
        {

           DetermineGhostScatterModeDirection();
        }

    }

    string GetClosestDirecition(Vector2 target)
    {
       float shortestDistance = 0;
       string lastMovingDirection = movementController.lastMovingDirection;
       string newDirection = "";
       NodeController nodeController = movementController.currentNode.GetComponent<NodeController>();

      
       if (nodeController.canMoveUp && lastMovingDirection != "down")
       {

         GameObject nodeUp = nodeController.nodeUp;
        

         float distance = Vector2.Distance(nodeUp.transform.position, target);


         if (distance < shortestDistance || shortestDistance == 0)
         {
            shortestDistance = distance;
            newDirection = "up";
         }
       }

       if (nodeController.canMoveDown && lastMovingDirection != "up")
       {

         GameObject nodeDown = nodeController.nodeDown;

         float distance = Vector2.Distance(nodeDown.transform.position, target);


         if (distance < shortestDistance || shortestDistance == 0)
         {
            shortestDistance = distance;
            newDirection = "down";
         }
       }

       if (nodeController.canMoveLeft && lastMovingDirection != "right")
       {

         GameObject nodeLeft = nodeController.nodeLeft;

         float distance = Vector2.Distance(nodeLeft.transform.position, target);


         if (distance < shortestDistance || shortestDistance == 0)
         {
            shortestDistance = distance;
            newDirection = "left";
         }
       }

       if (nodeController.canMoveRight && lastMovingDirection != "left")
       {

         GameObject nodeRight = nodeController.nodeRight;

         float distance = Vector2.Distance(nodeRight.transform.position, target);


         if (distance < shortestDistance || shortestDistance == 0)
         {
            shortestDistance = distance;
            newDirection = "right";
         }
       }

       return newDirection;
    }   

    public void SetVisible(bool newIsVisible)
    {
      isVisible = newIsVisible;
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
      if (collision.tag == "Player" && ghostNodeState != GhostNodeStatesEnum.respawning)
      {

        if (isFrightened)
        {
          gameManager.GhostEaten();
          ghostNodeState = GhostNodeStatesEnum.respawning;
        }

        else
        {
          StartCoroutine(gameManager.PlayerEaten());
        }
      }
    }
}

